### PR TITLE
[Refactoring] Refactor the directory tree to increase its readability

### PR DESCRIPTION
**Pull request by Rwatana**
## Topic
I performed structural refactoring of the code.

### Test
None

### Appendix
I plan to start working on creating the CLI as soon as this PR is completed.

### CODE REVIEW

**Comment by ryuji0123** [comment]
PR title: [Others]Refactor the code. -> [Refactoring] Refactor the directory tree
Commit message: [Others]Refactor the code. -> [Refactoring] Refactor the directory tree to increase its readability.

**Comment by ryuji0123** [comment]
PR title: [Others]Refactor the code. -> [Refactoring] Refactor the directory tree to increase its readability
Commit message: [Others]Refactor the code. -> [Refactoring] Refactor the directory tree to increase its readability. This commit is explicitly splitting components by languages like js and go.

**Review by ryuji0123 — CHANGES_REQUESTED** [review]
See my above comment.

**Comment by Rwatana** [comment]
@ryuji0123 
I think I have modified the points. Please check my code.

**Comment by ryuji0123** [comment]
Can you re-request review?

**Review by ryuji0123 — APPROVED** [review]

**Pull request merged**
