### PR TITLE
[Refactoring] Rename go directory to enhance readability and adhere to clean architecture principles

### LINKED ISSUE #24: [Refactoring] Rename the go directory to remake the directory
### Parent
#23 

### Background
same as parent
### Goal
same as parent

#### Overview
- **What**: Refactor the Go project structure to adhere to Clean Architecture.
- **How**:
  - Analyze the current directory and identify areas that require restructuring.
  - Implement Clean Architecture by separating concerns into distinct layers (e.g., domain, use cases, interface adapters, and frameworks/drivers).

#### Todo
  - [x] Rename the go directory.

### Deadline
9/7
### References
- [Clean Architecture Overview](https://example.com/clean-architecture-overview)
- [Go Project Layout](https://github.com/golang-standards/project-layout)

### PR DESCRIPTION
**Pull request by Rwatana**
### Issue Number
#24

### Implementation Summary
Renamed the directory to allow the creation of a new directory structure that adheres to Clean Architecture principles.

### Scope of Impact
This change is crucial for establishing a new directory component that follows Clean Architecture.

### Particular Points to Check
Please verify that the PR does not include any unnecessary changes.

### Test
As this is a refactoring task, no new tests have been added.

### Schedule
9/7

### CODE REVIEW

**Comment by Rwatana** [comment]
@ryuju0911 
Please check my PR.

**Comment by ryuju0911** [comment]
Please write the PR message so reviewers can understand the changes and why they are being made.

**Comment by ryuji0123** [comment]
Hmm, I guess @Rwatana tends to forget what we've pointed out. Please double-check what you should follow and save us saying the same things. Otherwise, we have to deprioritize educational opportunities.

**Comment by ryuji0123** [comment]
The easiest way is to create PR templates like Twitter-Clone, but still keep in mind you need to memorize and reflect PR conventions.

**Comment by Rwatana** [comment]
I apologize for any inconvenience this may cause. I will make sure to address each point carefully and strive to minimize any unnecessary time spent by the reviewer. Thank you for your understanding and cooperation.

**Review by ryujumoto — APPROVED** [review]

**Pull request merged**
